apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false   #no will be able to change the configmap
data:  
  username: admin1
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: rs0  