apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: resources-demo
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "1", "--vm", "1", "--vm-bytes", "2G", "--vm-hang", "1"]
    resources:
      requests:
        cpu: "200m"
        memory: "200Mi"
      limits:
        cpu: "1"
        memory: "3Gi"